version: '3'
services:
  app:
    container_name: prj-back-dasa
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes: ['./:/usr/src/app']
    links:
      - mongo
  mongo:
    container_name: db-mongo-dasa
    image: mongo
    ports:
      - '27017:27017'
